# a=[]
# i=0
# while i<10:
#     user=int(input("enter the number"))
#     a.append(user)
#     i+=1
#     max=a[0]
#     j=0
#     while j<len(a):
#         if max<a[j]:
#             max=a[j]
#         j+=1
#         min=a[0]
#         k=0
#         while k<len(a):
#             if min>a[k]:
#                 min=a[k]
#             k+=1
# print("max=",max,"min=",min)


# heigts=[4,2,7,10,5,9,7,20,6]
# i=0
# a=[]
# while i<len(heigts):
#     j=0
#     count=0
#     while j<len(heigts):
#         if heigts[i]<heigts[j]:
#             count+=1
#         j+=1
#     a.append(count)
#     i+=1
# print(a)


# num=[1,2,3,4]
# i=0
# b=[]
# sum=0
# while i<len(num):
#     sum=sum+num[i]
#     b.append(sum)
#     i=i+1
# print(b)
